# Generated by Django 4.0.4 on 2022-06-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referenceBook', '0003_alter_question_author_telephonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
